require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForgottenUsersController do

  # This should return the minimal set of attributes required to create a valid
  # ForgottenUser. As you add validations to ForgottenUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForgottenUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all forgotten_users as @forgotten_users" do
      forgotten_user = ForgottenUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:forgotten_users).should eq([forgotten_user])
    end
  end

  describe "GET show" do
    it "assigns the requested forgotten_user as @forgotten_user" do
      forgotten_user = ForgottenUser.create! valid_attributes
      get :show, {:id => forgotten_user.to_param}, valid_session
      assigns(:forgotten_user).should eq(forgotten_user)
    end
  end

  describe "GET new" do
    it "assigns a new forgotten_user as @forgotten_user" do
      get :new, {}, valid_session
      assigns(:forgotten_user).should be_a_new(ForgottenUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested forgotten_user as @forgotten_user" do
      forgotten_user = ForgottenUser.create! valid_attributes
      get :edit, {:id => forgotten_user.to_param}, valid_session
      assigns(:forgotten_user).should eq(forgotten_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ForgottenUser" do
        expect {
          post :create, {:forgotten_user => valid_attributes}, valid_session
        }.to change(ForgottenUser, :count).by(1)
      end

      it "assigns a newly created forgotten_user as @forgotten_user" do
        post :create, {:forgotten_user => valid_attributes}, valid_session
        assigns(:forgotten_user).should be_a(ForgottenUser)
        assigns(:forgotten_user).should be_persisted
      end

      it "redirects to the created forgotten_user" do
        post :create, {:forgotten_user => valid_attributes}, valid_session
        response.should redirect_to(ForgottenUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved forgotten_user as @forgotten_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForgottenUser.any_instance.stub(:save).and_return(false)
        post :create, {:forgotten_user => {}}, valid_session
        assigns(:forgotten_user).should be_a_new(ForgottenUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForgottenUser.any_instance.stub(:save).and_return(false)
        post :create, {:forgotten_user => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested forgotten_user" do
        forgotten_user = ForgottenUser.create! valid_attributes
        # Assuming there are no other forgotten_users in the database, this
        # specifies that the ForgottenUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ForgottenUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => forgotten_user.to_param, :forgotten_user => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested forgotten_user as @forgotten_user" do
        forgotten_user = ForgottenUser.create! valid_attributes
        put :update, {:id => forgotten_user.to_param, :forgotten_user => valid_attributes}, valid_session
        assigns(:forgotten_user).should eq(forgotten_user)
      end

      it "redirects to the forgotten_user" do
        forgotten_user = ForgottenUser.create! valid_attributes
        put :update, {:id => forgotten_user.to_param, :forgotten_user => valid_attributes}, valid_session
        response.should redirect_to(forgotten_user)
      end
    end

    describe "with invalid params" do
      it "assigns the forgotten_user as @forgotten_user" do
        forgotten_user = ForgottenUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForgottenUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => forgotten_user.to_param, :forgotten_user => {}}, valid_session
        assigns(:forgotten_user).should eq(forgotten_user)
      end

      it "re-renders the 'edit' template" do
        forgotten_user = ForgottenUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForgottenUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => forgotten_user.to_param, :forgotten_user => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested forgotten_user" do
      forgotten_user = ForgottenUser.create! valid_attributes
      expect {
        delete :destroy, {:id => forgotten_user.to_param}, valid_session
      }.to change(ForgottenUser, :count).by(-1)
    end

    it "redirects to the forgotten_users list" do
      forgotten_user = ForgottenUser.create! valid_attributes
      delete :destroy, {:id => forgotten_user.to_param}, valid_session
      response.should redirect_to(forgotten_users_url)
    end
  end

end
