Fabricator(:press_standard) do
  ampMaterial 1
  ampTime 1
  colorMaterial 1
  colorTime 1
  colorWaste 1
  dieMaterial 1
  dieSpeed 1
  dieTime 1
  dieWaste 1
  folderMaterial 1
  folderSpeed 1
  folderTime 1
  folderWaste 1
  headMaterial 1
  headTime 1
  hotStampMaterial 1
  hotStampSpeed 1
  hotStampTime 1
  hotStampWaste 1
  inkType 'stuff'
  inkTypeSig 'stuff'
  inkTypeVarnish 'stuff'
  inkMaterial 1
  inkTime 1
  inlineMaterial 1
  inlineSpeed 1
  inlineTime 1
  inlineWaste 1
  insertionMaterial 1
  insertionSpeed 1
  insertionTime 1
  laminationMaterial 1
  laminationSpeed 1
  laminationTime 1
  laminationWaste 1
  machineName 1
  machineID 1
  machineLabor 1
  machineOverhead 1
  machinePitch 1
  machineSpeed 1
  machineType 'stuff'
  machineWidth 1
  numberMaterial 1
  numberSpeed 1
  numberTime 1
  numberWaste 1
  plateChangeWaste 1
  plateChangeMaterial 1
  plateChangeTime 1
  pressSetupMaterial 1
  pressSetupTime 1
  printStations 1
  rollChangeMaterial 1
  rollChangeTime 1
  rollChangeWaste 1
  slitMaterial 1
  slitSpeed 1
  slitTime 1
  slitWaste 1
  trim 1
  turretMaterial 1
  turretSpeed 1
  turretTime 1
  turretWaste 1
end
